### ISSUE TITLE
Is repo dead?

### ISSUE THREAD

**Issue by misiek08** [Kickflip/kickflip-android-example#10]
We have few libraries like Build-tools at version 22 and Support library at 22.1.1. Including version 19.x.x in this example and in SDK make it uncompilable. Is it planned behavior?

**Comment by OnlyInAmerica** [comment]
the `dev` branch of this repository has been updated to compile against and target API 22.

Will have these changes merged into master shortly.

**Comment by OnlyInAmerica** [comment]
Updated repository to bring compileSdkVersion, SDK build tools and android gradle plugin all up-to-date.
