### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by preetsarb** [Kickflip/kickflip-android-example#2]
Video recording is working perfectly fine.
But when I try to view the steam on other device I am getting following error.

14432-14432/io.kickflip.sample I/API﹕ request failed A Kickflip server error occurred
14432-14459/io.kickflip.sample E/M3u8Parser﹕ Server returned HTTP 404 Not Found

**Comment by OnlyInAmerica** [comment]
Based on all information available to me I'm going to chalk this up to a temporary outage on behalf of our hosting provider. Please feel free to re-open if the issue persists.
