### ISSUE TITLE
UnsatisfiedLinkError: Couldn't load FFmpedWrapper

### ISSUE THREAD

**Issue by sherzberg** [Kickflip/kickflip-android-example#3]
I attempted to upgrade to the latest gradle and android 5.0 and got this error. I never tried to build the latest from your repository, but was hoping you can point me in the right direction to fix this. This stacktrace happens right when I try to start a broadcast.

```
java.lang.UnsatisfiedLinkError: Couldn't load FFmpegWrapper from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/io.kickflip.sample-1.apk"],nativeLibraryDirectories=[/data/app-lib/io.kickflip.sample-1, /vendor/lib, /system/lib]]]: findLibrary returned null
            at java.lang.Runtime.loadLibrary(Runtime.java:358)
            at java.lang.System.loadLibrary(System.java:526)
            at pro.dbro.ffmpegwrapper.FFmpegWrapper.<clinit>(FFmpegWrapper.java:45)
            at io.kickflip.sdk.av.FFmpegMuxer.<init>(FFmpegMuxer.java:72)
            at io.kickflip.sdk.av.FFmpegMuxer.create(FFmpegMuxer.java:104)
            at io.kickflip.sdk.av.SessionConfig$Builder.<init>(SessionConfig.java:229)
            at io.kickflip.sample.Util.create720pSessionConfig(Util.java:58)
            at io.kickflip.sample.activity.MainActivity.configureNewBroadcast(MainActivity.java:181)
            at io.kickflip.sample.activity.MainActivity.startBroadcastingActivity(MainActivity.java:175)
            at io.kickflip.sample.activity.MainActivity.onOptionsItemSelected(MainActivity.java:121)
```

Here is my upgraded repo and branch:

https://github.com/sherzberg/kickflip-android-example/tree/android-21-upgrade

**Comment by OnlyInAmerica** [comment]
I've updated kickflip-android-sdk and kickflip-android-example with support for Android 5.0, including an updated build of FFmpeg (2.5.2) with x86 libraries included.

Please check out the dev branch to test the latest changes.

`git clone https://github.com/Kickflip/kickflip-android-example --recursive -b dev`

Cheers!

**Comment by dovikn** [comment]
Thank You! 

I am assuming that the prerequisite that we we compile with Gradle still remains - is that correct? 

The truth is that I don't work with Gradle and thee are some other elements in my project that that seems to have trouble with Gradle. But I'd still love to try out and see what I can do with your library. 

Is there a way to get a .jar file that includes everything needed for kick flip to run on a non-gradle env? 

Thanks

**Comment by OnlyInAmerica** [comment]
Gradle is and will be the only supported build tool for Kickflip development.

The kickflip-android-sdk library includes items that the .jar standard doesn't specify (like Android specific assets including drawables, layouts etc.). That's what the [.aar](http://tools.android.com/tech-docs/new-build-system/aar-format) package is for and it's how nearly all Android Maven artifacts are deployed. Official .aar support with the Eclipse / ADT build tools is [not going to happen until that platform migrates to gradle](https://code.google.com/p/android/issues/detail?id=59183&thanks=59183&ts=1376992213). Even worse, that may never happen now that ADT is no longer under active development.

The writing's on the wall. For the health of your project you should migrate to Android Studio and gradle :)
