### ISSUE TITLE
Cannot play the recorded stream back

### ISSUE THREAD

**Issue by mevcloud** [Kickflip/kickflip-android-example#5]
Hi,

I am trying the android example. I am just doing live stream from the camera and then I want to play it back from the list on the main screen. But the stream is not playing, I just see the progressbar spinning. In the log file is see the following message: "E/M3u8Parser( 4185): Server returned HTTP 404 Not Found" 

Any ideas why is this happening?

Thanks,

M

Log file excerpt

D/StreamListFragment( 4185): stream url: https://d3t0i31z3foyta.cloudfront.net/crowdview_test/3qjmnk24umar/79829631-e988-4905-afdc-ba17333d4026/index.m3u8

D/AudioFlinger( 1929): Creating track with bufferSize 29132 bytes, frameCount 7283, mFrameSize 4 

V/LvOutput( 1929): initCheck: 0

V/LvOutput( 1929): attachEffects: attach processing to output 2, stream 1, session 99, mode 0

V/LvOutput( 1929): attachEffects: no output processing needs to be attached to this stream

V/LvOutput( 1929): LvOutput::setAllProcessorEnabled(false) mOutputs.size(0)

V/AudioPolicyManagerBase( 1929): startOutput() output 2, stream 1, session 99

V/AudioPolicyManagerBase( 1929): changeRefCount() stream 1, count 1

V/AudioPolicyManagerBase( 1929): getNewDevice() selected device 2

V/AudioPolicyManagerBase( 1929): setOutputDevice() output 2 device 0002 force 0 delayMs 0 

V/AudioPolicyManagerBase( 1929): setOutputDevice() prevDevice (0002)

V/AudioPolicyManagerBase( 1929): setOutputDevice() setting same device 0002 or null device for output 2

E/AudioResampler( 1929): Unsupported sample format, 1 bits, 2 channels

D/AudioResampler( 1929): AudioResamplerOrder1::resample common!!!!!

D/AudioResampler( 1929): new common resampler(44100 -> 48000, 2, 2)

D/SoundAliveResampler( 1929): [SoundAliveResampler] Init+++

V/AudioPolicyManagerBase( 1929): releaseOutput() 2

I/AudioHardwareTinyALSA( 1929): AudioStreamOutALSA::write setDevice

E/AudioHardwareTinyALSA( 1929): int android::AudioHardwareTinyALSA::open_hdmi_driver() cannot open video16 (-1)

D/AudioHardwareTinyALSA( 1929): OutALSA::setDevice: mode = 0, newDevice=0x2, currentDevice=0x2 ,force= 0

D/AudioHardwareTinyALSA( 1929): OutALSA::setDevice: mDevice 0x2, newDevice = 0x2

D/AudioHardwareTinyALSA( 1929): setOutputVolume

D/TinyUCM ( 1929): setModifier Normal, en=1

I/AudioHardwareTinyALSA( 1929): OutALSA::setDevice: mHandle NULL mode[0], Device[00000002] 

I/AudioHardwareTinyALSA( 1929): Open: mDefaults->direction=0 device=3

D/AudioHardwareTinyALSA( 1929): Channel: 2, Samplerate: 48000, Format: 0, Peroid Size: 960, Period Count: 4

I/AudioHardwareTinyALSA( 1929): before pcm_prepare

D/AudioHardwareTinyALSA( 1929): setPcmInterface: Stream=0x1, iSamplerate=8000++

D/AudioHardwareTinyALSA( 1929): setPcmInterface--

D/CustomFrequencyManagerService( 2420): acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1400000  uid : 1000  pid : 2420  pkgName : ACTIVITY_RESUME_BOOSTER@4

W/ActivityManager( 2420): mDVFSHelper.acquire()

D/PointerIcon( 2420): setMouseIconStyle1 pointerType: 1001iconType:101 flag:0

D/PointerIcon( 2420): setMouseCustomIcon IconType is same.101

D/PointerIcon( 2420): setHoveringSpenIconStyle1 pointerType: 10001iconType:1 flag:0

D/PointerIcon( 2420): setHoveringSpenCustomIcon IconType is same.1

I/SQLiteSecureOpenHelper( 3543): getWritableDatabase(pwd)

I/SQLiteSecureOpenHelper( 3543): getDatabaseLocked(b,b,pwd)...

I/SQLiteSecureOpenHelper( 3543): getWritableDatabase(pwd)

I/SQLiteSecureOpenHelper( 3543): getDatabaseLocked(b,b,pwd)...

V/WindowOrientationListener( 2420): ScreenOrientationEventListenerImpl.getProposedRotationLocked, Rotation: -1

V/WindowOrientationListener( 2420): ScreenOrientationEventListenerImpl.getProposedRotationLocked, Rotation: -1

V/WindowManager( 2420): rotationForOrientationLw(orient=0, last=0); user=0  sensorRotation=-1 mLidState=-1 mDockMode=0 mHdmiPlugged=false mAccelerometerDefault=false gripRotationLock=false

D/SamsungWindowManager( 2420): setRotationLw() : rotation=1

D/CustomFrequencyManagerService( 2420): acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1400000  uid : 1000  pid : 2420  pkgName : ROTATION_BOOSTER@29

D/InputDispatcher( 2420): setInputDispatchMode: enabled=1, frozen=1

I/SurfaceFlinger( 1920): id=220 createSurf (720x1280),2 flag=404, TcreenshotS

D/SSRMv2:TSP:AirViewOnOff( 2420): SettingsAirViewInfo:: 000000000

I/SurfaceFlinger( 1920): Orientation 0=>1

I/InputReader( 2420): Reconfiguring input devices.  changes=0x00000004

I/InputReader( 2420): Device reconfigured: id=2, name='sec_touchscreen', size 720x1280, orientation 1, mode 1, display id 0

I/ActivityManager( 2420): Config changes=480 {0 1.0 ?mcc?mnc en_GB ldltr sw360dp w640dp h335dp 320dpi nrml long land finger -keyb/v/h -nav/h s.30}

I/SamsungIME(11868): [Before] hardKeyboardHidden(2) keyboardType(1)

I/SamsungIME(11868):          mHwKeyboardShown [isHWKeyboardOpen()] = false --> false

E/SamsungIME(11868):          isHWKeyboardConnected() = false --> false

I/SamsungIME(11868): [hasToCallSuper] true

D/Mms/MmsApp(11916): [start]    onConfigurationChanged(),newConfig={0 1.0 ?mcc?mnc en_GB ldltr sw360dp w640dp h335dp 320dpi nrml long land finger -keyb/v/h -nav/h s.30}

D/Mms/MmsApp(11916): [end]    onConfigurationChanged(),newConfig={0 1.0 ?mcc?mnc en_GB ldltr sw360dp w640dp h335dp 320dpi nrml long land finger -keyb/v/h -nav/h s.30}

D/SamsungIME(11868): Dismiss ExpandCandiate

D/KeyguardUpdateMonitor( 2612): sendKeyguardVisibilityChanged(true)

I/display ( 1920): [DYNAMIC_RECOMP] GLES_2_HWC by BW check

D/PhoneStatusBar( 2612): mSettingsPanelGravity = 55

D/KeyguardUpdateMonitor( 2612): handleKeyguardVisibilityChanged(1)

D/PhoneStatusBarView( 2612): marqueeStatusBar:12-7, mClearCover:0

D/KeyguardUpdateMonitor( 2612): sendKeyguardVisibilityChanged(true)

D/STATUSBAR-IconMerger( 2612): checkOverflow(432), More:false, Req:false Child:4

E/Tethering( 2420): No numeric data

E/SmartFaceService( 2420): onReceive: android.intent.action.CONFIGURATION_CHANGED

E/SmartFaceService( 2420): mFolderCoverOpened: (true, true) -> true

D/STATUSBAR-QuickSettingPanel( 2612): setSingleLine:true

D/STATUSBAR-QuickSettingPanel( 2612): updateButtonInfo mButtonWidth : 160 mColumnNumber:8 orien: 2

D/STATUSBAR-QuickSettingPanel( 2612): onConfigurationChanged - dynamicallyReduceTextSize

D/STATUSBAR-QuickSettingButton( 2612): dynamicallyReduceTextSize: 160

D/STATUSBAR-QuickSettingButton( 2612): dynamicallyReduceTextSize: 160

D/STATUSBAR-QuickSettingButton( 2612): dynamicallyReduceTextSize: 160

D/STATUSBAR-QuickSettingButton( 2612): dynamicallyReduceTextSize: 160

D/STATUSBAR-QuickSettingButton( 2612): dynamicallyReduceTextSize: 160

D/STATUSBAR-QuickSettingButton( 2612): dynamicallyReduceTextSize: 160

D/STATUSBAR-QuickSettingButton( 2612): dynamicallyReduceTextSize: 160

D/STATUSBAR-QuickSettingButton( 2612): dynamicallyReduceTextSize: 160

D/STATUSBAR-QuickSettingButton( 2612): dynamicallyReduceTextSize: 160

D/STATUSBAR-QuickSettingButton( 2612): dynamicallyReduceTextSize: 160

D/STATUSBAR-QuickSettingButton( 2612): dynamicallyReduceTextSize: 160

D/STATUSBAR-QuickSettingButton( 2612): dynamicallyReduceTextSize: 160

D/STATUSBAR-QuickSettingButton( 2612): dynamicallyReduceTextSize: 160

D/STATUSBAR-QuickSettingButton( 2612): dynamicallyReduceTextSize: 160

D/KeyguardUpdateMonitor( 2612): handleKeyguardVisibilityChanged(1)

D/STATUSBAR-QuickSettingButton( 2612): dynamicallyReduceTextSize: 160

D/STATUSBAR-QuickSettingButton( 2612): dynamicallyReduceTextSize: 160

D/STATUSBAR-QuickSettingButton( 2612): dynamicallyReduceTextSize: 160

D/STATUSBAR-QuickSettingButton( 2612): dynamicallyReduceTextSize: 160

D/STATUSBAR-NetworkController( 2612): onReceive() - ACTION_CONFIGURATION_CHANGED

D/KeyguardUpdateMonitor( 2612): sendKeyguardVisibilityChanged(true)

D/StatusBarManagerService( 2420): tr p:4185,o:f

D/STATUSBAR-IconMerger( 2612): checkOverflow(960), More:false, Req:false Child:4

D/StatusBarManagerService( 2420): semi p:4185,o:f

D/KeyguardUpdateMonitor( 2612): sendKeyguardVisibilityChanged(true)

D/PhoneStatusBar( 2612): setTransGradationMode=false, mTransparentMode=false, mSemiTransparentMode=false, mMultiWindowMode=false

D/KeyguardUpdateMonitor( 2612): handleKeyguardVisibilityChanged(1)

D/KeyguardUpdateMonitor( 2612): sendKeyguardVisibilityChanged(true)

I/SurfaceFlinger( 1920): id=215 Removed NainActivit (7/10)

I/SurfaceFlinger( 1920): id=215 Removed NainActivit (-2/10)

D/KeyguardUpdateMonitor( 2612): sendKeyguardVisibilityChanged(true)

D/PhoneStatusBar( 2612): setSemiTransparentMode=false, mTransparentMode=false, mSemiTransparentMode=false, mMultiWindowMode=false

D/KeyguardUpdateMonitor( 2612): handleKeyguardVisibilityChanged(1)

D/KeyguardUpdateMonitor( 2612): handleKeyguardVisibilityChanged(1)

D/KeyguardUpdateMonitor( 2612): handleKeyguardVisibilityChanged(1)

I/SurfaceFlinger( 1920): id=221 createSurf (1280x720),1 flag=404, NediaPlayer

D/STATUSBAR-StatusBarManagerService( 2420): manageDisableList what=0x0 pkg=WindowManager.LayoutParams

D/BarController.StatusBar( 2420): mState: WINDOW_STATE_HIDDEN

D/KeyguardUpdateMonitor( 2612): sendKeyguardVisibilityChanged(true)

D/KeyguardUpdateMonitor( 2612): sendKeyguardVisibilityChanged(true)

W/ContextImpl( 2420): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1501 com.android.internal.policy.impl.PhoneWindowManager.notifyToSSRM:6306 com.android.internal.policy.impl.PhoneWindowManager.access$200:195 com.android.internal.policy.impl.PhoneWindowManager$PolicyHandler.handleMessage:770 android.os.Handler.dispatchMessage:102 

D/SSRMv2:TSP:AirViewOnOff( 2420): SettingsAirViewInfo:: 000000000

D/PointerIcon( 2420): setMouseIconStyle1 pointerType: 1001iconType:101 flag:0

D/PointerIcon( 2420): setMouseCustomIcon IconType is same.101

D/KeyguardUpdateMonitor( 2612): handleKeyguardVisibilityChanged(1)

D/KeyguardUpdateMonitor( 2612): handleKeyguardVisibilityChanged(1)

D/PointerIcon( 2420): setHoveringSpenIconStyle1 pointerType: 10001iconType:1 flag:0

D/PointerIcon( 2420): setHoveringSpenCustomIcon IconType is same.1

D/PhoneStatusBar( 2612): Status bar WINDOW_STATE_HIDDEN

D/ProgressBar( 4185): updateDrawableBounds: left = 0

D/ProgressBar( 4185): updateDrawableBounds: top = 0

D/ProgressBar( 4185): updateDrawableBounds: right = 300

D/ProgressBar( 4185): updateDrawableBounds: bottom = 300

W/ContextImpl( 2420): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1501 com.android.server.InputMethodManagerService$4.run:2728 java.lang.Thread.run:841 <bottom of call stack> <bottom of call stack> 

D/KeyguardUpdateMonitor( 2612): sendKeyguardVisibilityChanged(true)

D/KeyguardUpdateMonitor( 2612): handleKeyguardVisibilityChanged(1)

D/CustomFrequencyManagerService( 2420): releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1400000  uid : 1000  pid : 2420  tag : ACTIVITY_RESUME_BOOSTER@4

D/KeyguardUpdateMonitor( 2612): sendKeyguardVisibilityChanged(true)

W/ActivityManager( 2420): mDVFSHelper.release()

D/KeyguardUpdateMonitor( 2612): handleKeyguardVisibilityChanged(1)

I/SurfaceFlinger( 1920): id=222 createSurf (1440x1280),-1 flag=20004, ClackSurfac

D/CustomFrequencyManagerService( 2420): acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1400000  uid : 1000  pid : 2420  pkgName : ACTIVITY_RESUME_BOOSTER@8

I/WindowManager( 2420): Screen frozen for +249ms due to Window{43115968 u0 io.kickflip.sample/io.kickflip.sdk.activity.MediaPlayerActivity}

I/SurfaceFlinger( 1920): id=223 createSurf (720x2560),-1 flag=20004, ClackSurfac

I/SurfaceFlinger( 1920): id=224 createSurf (1440x1280),-1 flag=20004, ClackSurfac

I/SurfaceFlinger( 1920): id=225 createSurf (720x2560),-1 flag=20004, ClackSurfac

D/InputDispatcher( 2420): setInputDispatchMode: enabled=1, frozen=0

D/KeyguardUpdateMonitor( 2612): sendKeyguardVisibilityChanged(true)

D/KeyguardUpdateMonitor( 2612): handleKeyguardVisibilityChanged(1)

D/hwcutils( 1920): MppFactory::MppFactory()

D/        ( 1920): virtual LibMpp* MppFactory::CreateMpp(int, int, int, int)(6)

D/libexynosfimc( 1920): LibMpp::LibMpp()

I/SurfaceFlinger( 1920): id=220 Removed TcreenshotS (10/14)

I/SurfaceFlinger( 1920): id=220 Removed TcreenshotS (-2/14)

I/SurfaceFlinger( 1920): id=222 Removed ClackSurfac (10/13)

I/SurfaceFlinger( 1920): id=222 Removed ClackSurfac (-2/13)

I/SurfaceFlinger( 1920): id=223 Removed ClackSurfac (10/12)

I/SurfaceFlinger( 1920): id=223 Removed ClackSurfac (-2/12)

I/SurfaceFlinger( 1920): id=224 Removed ClackSurfac (10/11)

I/SurfaceFlinger( 1920): id=224 Removed ClackSurfac (-2/11)

I/SurfaceFlinger( 1920): id=225 Removed ClackSurfac (10/10)

I/SurfaceFlinger( 1920): id=225 Removed ClackSurfac (-2/10)

D/KeyguardUpdateMonitor( 2612): sendKeyguardVisibilityChanged(true)

D/KeyguardUpdateMonitor( 2612): handleKeyguardVisibilityChanged(1)

V/WindowOrientationListener( 2420): ScreenOrientationEventListenerImpl.getProposedRotationLocked, Rotation: -1

V/WindowOrientationListener( 2420): ScreenOrientationEventListenerImpl.getProposedRotationLocked, Rotation: -1

V/WindowManager( 2420): rotationForOrientationLw(orient=0, last=1); user=0  sensorRotation=-1 mLidState=-1 mDockMode=0 mHdmiPlugged=false mAccelerometerDefault=false gripRotationLock=false

I/AudioFlinger( 1929): sleepTime is reduced to minimum forcely

E/M3u8Parser( 4185): Server returned HTTP 404 Not Found

I/AudioFlinger( 1929): sleepTime is reduced to minimum forcely

I/AudioFlinger( 1929): sleepTime is reduced to minimum forcely

I/AudioFlinger( 1929): sleepTime is reduced to minimum forcely

I/AudioFlinger( 1929): sleepTime is reduced to minimum forcely

V/LvOutput( 1929): initCheck: 0

V/LvOutput( 1929): detachEffects: detach processing for output 2, stream 1, session 99

V/LvOutput( 1929): detachEffects: no output processing was attached to this stream

V/AudioPolicyManagerBase( 1929): stopOutput() output 2, stream 1, session 99

V/AudioPolicyManagerBase( 1929): changeRefCount() stream 1, count 0

V/AudioPolicyManagerBase( 1929): getNewDevice() selected device 0

V/AudioPolicyManagerBase( 1929): setOutputDevice() output 2 device 0000 force 0 delayMs 160 

V/AudioPolicyManagerBase( 1929): setOutputDevice() prevDevice (0002)

V/AudioPolicyManagerBase( 1929): setOutputDevice() setting same device 0000 or null device for output 2

I/AudioFlinger( 1929): sleepTime is reduced to minimum forcely

I/AudioFlinger( 1929): sleepTime is reduced to minimum forcely

I/AudioFlinger( 1929): sleepTime is reduced to minimum forcely

I/AudioFlinger( 1929): sleepTime is reduced to minimum forcely

I/AudioFlinger( 1929): sleepTime is reduced to minimum forcely

D/STATUSBAR-NetworkController( 2612): refreshSignalCluster - setNWBoosterIndicators(false)

D/STATUSBAR-NetworkController( 2612): refreshSignalCluster: data=-1 bt=false

D/STATUSBAR-IconMerger( 2612): checkOverflow(960), More:false, Req:false Child:4

D/CustomFrequencyManagerService( 2420): releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1400000  uid : 1000  pid : 2420  tag : ACTIVITY_RESUME_BOOSTER@8

D/SensorService( 2420):   0.2 -0.1 9.6

D/CustomFrequencyManagerService( 2420): releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1400000  uid : 1000  pid : 2420  tag : ROTATION_BOOSTER@29

D/STATUSBAR-NetworkController( 2612): refreshSignalCluster - setNWBoosterIndicators(false)

D/STATUSBAR-NetworkController( 2612): refreshSignalCluster: data=-1 bt=false

D/STATUSBAR-IconMerger( 2612): checkOverflow(960), More:false, Req:false Child:4

D/dalvikvm( 2420): GC_EXPLICIT freed 278K, 21% free 27801K/34924K, paused 18ms+16ms, total 292ms

D/AudioHardwareTinyALSA( 1929): Entering AudioStreamOutALSA standby mode

I/AudioHardwareTinyALSA( 1929): Close mHandle:442ec6d0

**Comment by aornelas** [comment]
I'm seeing the same issue. Tried debugging it, but Android Studio gets lost somewhere in AndroidEncoder.java (since it's the sdk, so the source is not matching the compiled classes).

I don't think this is a problem with opening broadcasts, but instead with STARTING them. The activity crashes when you press record with the following exception:
```
03-18 21:07:45.273  28149-28234/io.kickflip.sample E/AndroidRuntime﹕ FATAL EXCEPTION: CameraEncoder
    Process: io.kickflip.sample, PID: 28149
    java.nio.ReadOnlyBufferException
            at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:354)
            at io.kickflip.sdk.av.FFmpegMuxer.captureH264MetaData(FFmpegMuxer.java:292)
            at io.kickflip.sdk.av.FFmpegMuxer.handleWriteSampleData(FFmpegMuxer.java:206)
            at io.kickflip.sdk.av.FFmpegMuxer.writeSampleData(FFmpegMuxer.java:183)
            at io.kickflip.sdk.av.AndroidEncoder.drainEncoder(AndroidEncoder.java:100)
            at io.kickflip.sdk.av.CameraEncoder.handleFrameAvailable(CameraEncoder.java:433)
            at io.kickflip.sdk.av.CameraEncoder.access$200(CameraEncoder.java:27)
            at io.kickflip.sdk.av.CameraEncoder$EncoderHandler.handleMessage(CameraEncoder.java:835)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at io.kickflip.sdk.av.CameraEncoder.run(CameraEncoder.java:610)
            at java.lang.Thread.run(Thread.java:818)
```

While the stream is in fact created, if you open it from your kickflip page, it's simply a black screen (e.g., https://kickflip.io/d6216235-f3cf-4585-a7b3-e920a393f99e/).

**Comment by picazzzo** [comment]
I have the same issue. Just cloned repo and created SECRETS file with correct credentials.

Nexus 5, Android 5.1

**Comment by OnlyInAmerica** [comment]
@aornelas @picazzzo this issue is due to a MediaCodec change that occurred in Android 5.0. The dev branch of kickflip-android-example references the head of kickflip-android-sdk with this issue resolved.

Note that I messed up the ffmpeg build so the produced jniLibs will only work on 5.0+ devices. I will address that as soon as I can find some spare cycles.

Thanks for your patience!

**Comment by OnlyInAmerica** [comment]
@aornelas @picazzzo your issue is now resolved.

@mevcloud your issue was likely due to a network error during initial stream upload or some temporary server issue during playback. I'm going to close this for now but feel free to re-open if you continue to experience issues.
