### ISSUE TITLE
Error when import and run

### ISSUE THREAD

**Issue by seamug** [Kickflip/kickflip-android-example#7]
Hi 

when I run the project after importing , I received this error

Error:(15, 0) Gradle DSL method not found: 'runProguard()'
Possible causes:<ul><li>The project 'kickflip-android-example-master' may be using a version of Gradle that does not contain the method.
<a href="open.wrapper.file">Open Gradle wrapper file</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>

PLease advise. Thank you

**Comment by Rahulaswani** [comment]
@seamug did you get a solution to this problem ?

**Comment by seamug** [comment]
Nope. Kickflip is not responding. I have switch to cine.io. 

Too bad. They have potential



>

**Comment by OnlyInAmerica** [comment]
this error is now resolved in the master branch. Sorry for the delay!

**Comment by Rahulaswani** [comment]
No Problem @OnlyInAmerica until you are responsive, ill surely check out the update whoever i was able to fix the problem and make it run. KIckFlip works good just a bit laggy I used it for a Hackathon :+1:
